/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CrmIndexRouteImport } from './routes/crm/index'
import { Route as CmsIndexRouteImport } from './routes/cms/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as CrmSupportRouteImport } from './routes/crm/support'
import { Route as CrmOverviewRouteImport } from './routes/crm/overview'
import { Route as CrmInsightsRouteImport } from './routes/crm/insights'
import { Route as CrmBillingRouteImport } from './routes/crm/billing'
import { Route as CrmLayoutRouteImport } from './routes/crm/_layout'
import { Route as CmsOverviewRouteImport } from './routes/cms/overview'
import { Route as CmsMediaRouteImport } from './routes/cms/media'
import { Route as CmsAnalyticsRouteImport } from './routes/cms/analytics'
import { Route as CmsLayoutRouteImport } from './routes/cms/_layout'
import { Route as AuthRegisterRouteImport } from './routes/auth/register'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as AdminUsersRouteImport } from './routes/admin/users'
import { Route as AdminSettingsRouteImport } from './routes/admin/settings'
import { Route as AdminOverviewRouteImport } from './routes/admin/overview'
import { Route as AdminLogsRouteImport } from './routes/admin/logs'
import { Route as AdminLayoutRouteImport } from './routes/admin/_layout'

const CrmRouteImport = createFileRoute('/crm')()
const CmsRouteImport = createFileRoute('/cms')()
const AdminRouteImport = createFileRoute('/admin')()

const CrmRoute = CrmRouteImport.update({
  id: '/crm',
  path: '/crm',
  getParentRoute: () => rootRouteImport,
} as any)
const CmsRoute = CmsRouteImport.update({
  id: '/cms',
  path: '/cms',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CrmIndexRoute = CrmIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CrmRoute,
} as any)
const CmsIndexRoute = CmsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CmsRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const CrmSupportRoute = CrmSupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => CrmRoute,
} as any)
const CrmOverviewRoute = CrmOverviewRouteImport.update({
  id: '/overview',
  path: '/overview',
  getParentRoute: () => CrmRoute,
} as any)
const CrmInsightsRoute = CrmInsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => CrmRoute,
} as any)
const CrmBillingRoute = CrmBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => CrmRoute,
} as any)
const CrmLayoutRoute = CrmLayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => CrmRoute,
} as any)
const CmsOverviewRoute = CmsOverviewRouteImport.update({
  id: '/overview',
  path: '/overview',
  getParentRoute: () => CmsRoute,
} as any)
const CmsMediaRoute = CmsMediaRouteImport.update({
  id: '/media',
  path: '/media',
  getParentRoute: () => CmsRoute,
} as any)
const CmsAnalyticsRoute = CmsAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => CmsRoute,
} as any)
const CmsLayoutRoute = CmsLayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => CmsRoute,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/auth/register',
  path: '/auth/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOverviewRoute = AdminOverviewRouteImport.update({
  id: '/overview',
  path: '/overview',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLogsRoute = AdminLogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLayoutRoute = AdminLayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminLayoutRoute
  '/admin/logs': typeof AdminLogsRoute
  '/admin/overview': typeof AdminOverviewRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/cms': typeof CmsLayoutRoute
  '/cms/analytics': typeof CmsAnalyticsRoute
  '/cms/media': typeof CmsMediaRoute
  '/cms/overview': typeof CmsOverviewRoute
  '/crm': typeof CrmLayoutRoute
  '/crm/billing': typeof CrmBillingRoute
  '/crm/insights': typeof CrmInsightsRoute
  '/crm/overview': typeof CrmOverviewRoute
  '/crm/support': typeof CrmSupportRoute
  '/admin/': typeof AdminIndexRoute
  '/cms/': typeof CmsIndexRoute
  '/crm/': typeof CrmIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminIndexRoute
  '/admin/logs': typeof AdminLogsRoute
  '/admin/overview': typeof AdminOverviewRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/cms': typeof CmsIndexRoute
  '/cms/analytics': typeof CmsAnalyticsRoute
  '/cms/media': typeof CmsMediaRoute
  '/cms/overview': typeof CmsOverviewRoute
  '/crm': typeof CrmIndexRoute
  '/crm/billing': typeof CrmBillingRoute
  '/crm/insights': typeof CrmInsightsRoute
  '/crm/overview': typeof CrmOverviewRoute
  '/crm/support': typeof CrmSupportRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/admin/_layout': typeof AdminLayoutRoute
  '/admin/logs': typeof AdminLogsRoute
  '/admin/overview': typeof AdminOverviewRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/cms': typeof CmsRouteWithChildren
  '/cms/_layout': typeof CmsLayoutRoute
  '/cms/analytics': typeof CmsAnalyticsRoute
  '/cms/media': typeof CmsMediaRoute
  '/cms/overview': typeof CmsOverviewRoute
  '/crm': typeof CrmRouteWithChildren
  '/crm/_layout': typeof CrmLayoutRoute
  '/crm/billing': typeof CrmBillingRoute
  '/crm/insights': typeof CrmInsightsRoute
  '/crm/overview': typeof CrmOverviewRoute
  '/crm/support': typeof CrmSupportRoute
  '/admin/': typeof AdminIndexRoute
  '/cms/': typeof CmsIndexRoute
  '/crm/': typeof CrmIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/admin/logs'
    | '/admin/overview'
    | '/admin/settings'
    | '/admin/users'
    | '/auth/login'
    | '/auth/register'
    | '/cms'
    | '/cms/analytics'
    | '/cms/media'
    | '/cms/overview'
    | '/crm'
    | '/crm/billing'
    | '/crm/insights'
    | '/crm/overview'
    | '/crm/support'
    | '/admin/'
    | '/cms/'
    | '/crm/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/admin/logs'
    | '/admin/overview'
    | '/admin/settings'
    | '/admin/users'
    | '/auth/login'
    | '/auth/register'
    | '/cms'
    | '/cms/analytics'
    | '/cms/media'
    | '/cms/overview'
    | '/crm'
    | '/crm/billing'
    | '/crm/insights'
    | '/crm/overview'
    | '/crm/support'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/admin/_layout'
    | '/admin/logs'
    | '/admin/overview'
    | '/admin/settings'
    | '/admin/users'
    | '/auth/login'
    | '/auth/register'
    | '/cms'
    | '/cms/_layout'
    | '/cms/analytics'
    | '/cms/media'
    | '/cms/overview'
    | '/crm'
    | '/crm/_layout'
    | '/crm/billing'
    | '/crm/insights'
    | '/crm/overview'
    | '/crm/support'
    | '/admin/'
    | '/cms/'
    | '/crm/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
  CmsRoute: typeof CmsRouteWithChildren
  CrmRoute: typeof CrmRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/crm': {
      id: '/crm'
      path: '/crm'
      fullPath: '/crm'
      preLoaderRoute: typeof CrmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cms': {
      id: '/cms'
      path: '/cms'
      fullPath: '/cms'
      preLoaderRoute: typeof CmsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crm/': {
      id: '/crm/'
      path: '/'
      fullPath: '/crm/'
      preLoaderRoute: typeof CrmIndexRouteImport
      parentRoute: typeof CrmRoute
    }
    '/cms/': {
      id: '/cms/'
      path: '/'
      fullPath: '/cms/'
      preLoaderRoute: typeof CmsIndexRouteImport
      parentRoute: typeof CmsRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/crm/support': {
      id: '/crm/support'
      path: '/support'
      fullPath: '/crm/support'
      preLoaderRoute: typeof CrmSupportRouteImport
      parentRoute: typeof CrmRoute
    }
    '/crm/overview': {
      id: '/crm/overview'
      path: '/overview'
      fullPath: '/crm/overview'
      preLoaderRoute: typeof CrmOverviewRouteImport
      parentRoute: typeof CrmRoute
    }
    '/crm/insights': {
      id: '/crm/insights'
      path: '/insights'
      fullPath: '/crm/insights'
      preLoaderRoute: typeof CrmInsightsRouteImport
      parentRoute: typeof CrmRoute
    }
    '/crm/billing': {
      id: '/crm/billing'
      path: '/billing'
      fullPath: '/crm/billing'
      preLoaderRoute: typeof CrmBillingRouteImport
      parentRoute: typeof CrmRoute
    }
    '/crm/_layout': {
      id: '/crm/_layout'
      path: '/crm'
      fullPath: '/crm'
      preLoaderRoute: typeof CrmLayoutRouteImport
      parentRoute: typeof CrmRoute
    }
    '/cms/overview': {
      id: '/cms/overview'
      path: '/overview'
      fullPath: '/cms/overview'
      preLoaderRoute: typeof CmsOverviewRouteImport
      parentRoute: typeof CmsRoute
    }
    '/cms/media': {
      id: '/cms/media'
      path: '/media'
      fullPath: '/cms/media'
      preLoaderRoute: typeof CmsMediaRouteImport
      parentRoute: typeof CmsRoute
    }
    '/cms/analytics': {
      id: '/cms/analytics'
      path: '/analytics'
      fullPath: '/cms/analytics'
      preLoaderRoute: typeof CmsAnalyticsRouteImport
      parentRoute: typeof CmsRoute
    }
    '/cms/_layout': {
      id: '/cms/_layout'
      path: '/cms'
      fullPath: '/cms'
      preLoaderRoute: typeof CmsLayoutRouteImport
      parentRoute: typeof CmsRoute
    }
    '/auth/register': {
      id: '/auth/register'
      path: '/auth/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/overview': {
      id: '/admin/overview'
      path: '/overview'
      fullPath: '/admin/overview'
      preLoaderRoute: typeof AdminOverviewRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/logs': {
      id: '/admin/logs'
      path: '/logs'
      fullPath: '/admin/logs'
      preLoaderRoute: typeof AdminLogsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/_layout': {
      id: '/admin/_layout'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminLayoutRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminLayoutRoute: typeof AdminLayoutRoute
  AdminLogsRoute: typeof AdminLogsRoute
  AdminOverviewRoute: typeof AdminOverviewRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminLayoutRoute: AdminLayoutRoute,
  AdminLogsRoute: AdminLogsRoute,
  AdminOverviewRoute: AdminOverviewRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface CmsRouteChildren {
  CmsLayoutRoute: typeof CmsLayoutRoute
  CmsAnalyticsRoute: typeof CmsAnalyticsRoute
  CmsMediaRoute: typeof CmsMediaRoute
  CmsOverviewRoute: typeof CmsOverviewRoute
  CmsIndexRoute: typeof CmsIndexRoute
}

const CmsRouteChildren: CmsRouteChildren = {
  CmsLayoutRoute: CmsLayoutRoute,
  CmsAnalyticsRoute: CmsAnalyticsRoute,
  CmsMediaRoute: CmsMediaRoute,
  CmsOverviewRoute: CmsOverviewRoute,
  CmsIndexRoute: CmsIndexRoute,
}

const CmsRouteWithChildren = CmsRoute._addFileChildren(CmsRouteChildren)

interface CrmRouteChildren {
  CrmLayoutRoute: typeof CrmLayoutRoute
  CrmBillingRoute: typeof CrmBillingRoute
  CrmInsightsRoute: typeof CrmInsightsRoute
  CrmOverviewRoute: typeof CrmOverviewRoute
  CrmSupportRoute: typeof CrmSupportRoute
  CrmIndexRoute: typeof CrmIndexRoute
}

const CrmRouteChildren: CrmRouteChildren = {
  CrmLayoutRoute: CrmLayoutRoute,
  CrmBillingRoute: CrmBillingRoute,
  CrmInsightsRoute: CrmInsightsRoute,
  CrmOverviewRoute: CrmOverviewRoute,
  CrmSupportRoute: CrmSupportRoute,
  CrmIndexRoute: CrmIndexRoute,
}

const CrmRouteWithChildren = CrmRoute._addFileChildren(CrmRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
  CmsRoute: CmsRouteWithChildren,
  CrmRoute: CrmRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
